# Generated by Django 4.1.4 on 2023-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('MCA', 'MCA'), ('MBA', 'MCA'), ('PHD', 'PHD'), ('MTECH', 'MTECH')], max_length=100),
        ),
    ]
