# Generated by Django 3.2.16 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20230119_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='graduation_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.IntegerField(default=1990, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
