# Generated by Django 3.2.16 on 2023-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_auto_20230119_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('MCA', 'MCA'), ('MTECH', 'MTECH'), ('COMMERCE', 'COMMERCE'), ('MTECH', 'MTECH'), ('MSC', 'MSC')], max_length=100),
        ),
    ]
