# Generated by Django 3.2.16 on 2023-01-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_alter_profile_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='id',
            new_name='post_id',
        ),
    ]
