# Generated by Django 3.2.16 on 2023-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_rename_id_blogpost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
