# Generated by Django 3.2.16 on 2023-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
