# Generated by Django 3.2.16 on 2023-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_blogpost_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='job_offer',
            field=models.CharField(choices=[(0, 'Summer Intern'), (1, 'Job'), (2, 'PPO'), (3, 'Winter Intern')], default=1, max_length=100),
        ),
    ]
