# Generated by Django 3.2.16 on 2023-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_auto_20230208_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='job_offer',
            field=models.CharField(choices=[('SUMMER INTERN', 'SUMMER INTERN'), ('JOB', 'JOB'), ('PPO', 'PPO'), ('WINTER INTERN', 'WINTER INTERN')], default=1, max_length=100),
        ),
    ]
